ci(workflow): dockerhub readme sync
okp4/docker-images pull request #72
Opened 2022-08-08 18:24 UTC by hleonardtek

2022-08-09 08:05 UTC, ad2ien approved these changes
Really nice and useful workflow!
Ok for me, just a couple of suggestion on the steps names, it's up to you.

2022-08-09 08:05 UTC, ad2ien commented on .github/workflows/dockerhub-description.yaml
> +      - name: Setup matrix (for changed readmes)
```suggestion
      - name: Build iterable readmes info
```

2022-08-09 12:25 UTC, amimart requested changes
Excellent, thank you for your contribution!

As is serve the same purpose as the publish workflow, triggered on the same events, can we maybe move those jobs in the existing publish workflow?

2022-08-17 08:06 UTC, amimart approved these changes

2022-08-17 08:30 UTC, ccamel approved these changes

2022-08-18 06:54 UTC, merged