docs(readme): enhance images readmes
okp4/docker-images pull request #74
Opened 2022-08-09 14:17 UTC by hleonardtek

As described [here](https://github.com/okp4/kanban/issues/729), we should provide relevant READMEs to our docker images.
Whoever is able to enhance any image README should contribute to this PR.

2022-08-09 15:15 UTC, ad2ien commented
@ccamel @SonnevilleDamien @amimart if you want the dockerhub page of the image you've been working on to be described, you can improve the corresponding readme file. (On this PR or not)

2022-08-10 07:11 UTC, ad2ien requested changes
Nice readme, I added a suggestion to improve the intro.

2022-08-10 07:11 UTC, ad2ien commented on dockerfiles/cosmos-exporter/README.md
>  An exporter used to get blockchain metrics from the validators.
```suggestion
An exporter used to get cosmos based blockchain metrics from a running node.
```

2022-08-10 07:11 UTC, ad2ien commented on dockerfiles/cosmos-exporter/README.md
> +It queries nodes to extract informations concerning validators and wallets.
```suggestion
It queries a node to extract informations concerning 
- The blockchain network in general
- Some specific validators and wallets.
```

2022-08-10 14:08 UTC, ccamel commented
@hleonardtek great initiative. Same than @ad2ien did, I call also everyone involved (@SonnevilleDamien @amimart and me) to improve the `readme` files in this PR.

2022-08-16 05:35 UTC, ad2ien commented
We add an image called cosmos-faucet made from [BitCannaCommunity/cosmos-faucet](https://github.com/BitCannaCommunity/cosmos-faucet) I removed it to be sure that okp4/cosmos-faucet is our faucet.

2022-08-17 13:04 UTC, ad2ien approved these changes
Let's go, It will then become a running task to make sure readme files are ok.

2022-08-17 13:27 UTC, amimart approved these changes

2022-08-17 20:41 UTC, ccamel approved these changes

2022-08-18 06:56 UTC, merged