Update some image packages
okp4/docker-images pull request #82
Opened 2022-08-23 13:21 UTC by ad2ien

Continuing the epic story about improving okp4 dockerhub account, this PR will :
- add some images that are not yet on dockerhub
- give the toolbox image, the description it deserves

2022-08-23 14:32 UTC, amimart approved these changes
Nice thank you, I think there is just some imprecisions on folder naming

2022-08-23 14:32 UTC, amimart commented on dockerfiles/texlive/20220822/Dockerfile
> +     texlive=2022.20220722-1                                    \
This dockerfile should be in the `2022.20220722-1` folder

2022-08-23 14:32 UTC, amimart commented on dockerfiles/ruby-rdf/3.2.29/Dockerfile
> +      rdf:3.2.9 \
Should be in the `3.2.9` folder

2022-08-23 14:38 UTC, amimart requested changes
Sorry I wrongly approved the changes, please rely on my previous remarks

2022-08-23 16:12 UTC, ad2ien commented
> Sorry I wrongly approved the changes, please rely on my previous remarks

Thanks, you're totally right!

2022-08-26 07:54 UTC, amimart approved these changes
🚀

2022-08-26 07:56 UTC, merged